"""remove artifacts

Revision ID: 12e238b646e8
Revises: d641f36788a3
Create Date: 2025-01-15 13:51:02.648298

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '12e238b646e8'
down_revision = 'd641f36788a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artifact')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifact',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('collection_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['artifactcollection.id'], name='artifact_collection_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='artifact_pkey')
    )
    # ### end Alembic commands ###
