"""add sbatch job

Revision ID: 15149a846727
Revises: 21aa175324fd
Create Date: 2025-02-12 13:14:10.668678

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '15149a846727'
down_revision = '21aa175324fd'
branch_labels = None
depends_on = None


SLURM_JOB_STATUS_ENUM = sa.Enum('UNSUBMITTED', 'COMPLETED', 'COMPLETING', 'PENDING', 'CANCELLED', 'FAILED', 'RUNNING', 'UNHANDLED', name='slurmjobstatus')
SLURM_JOB_STATE = sa.Enum('BOOT_FAIL', 'CANCELLED', 'COMPLETED', 'DEADLINE', 'FAILED', 'NODE_FAIL', 'OUT_OF_MEMORY', 'PENDING', 'PREEMPTED', 'RUNNING', 'SUSPENDED', 'TIMEOUT', name='slurmjobstate')

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sbatchanalysisspec', 'status')
    SLURM_JOB_STATUS_ENUM.drop(op.get_bind())
    SLURM_JOB_STATE.create(op.get_bind())
    op.create_table('sbatchjob',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slurm_id', sa.Integer(), nullable=False),
    sa.Column('analysis_spec_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.func.now()),
    sa.Column('updated_at', sa.DateTime(), nullable=True, onupdate=sa.func.now()),
    sa.ForeignKeyConstraint(['analysis_spec_id'], ['sbatchanalysisspec.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('sbatchjob', sa.Column('status', SLURM_JOB_STATE, nullable=False))
    op.create_index(op.f('ix_sbatchjob_slurm_id'), 'sbatchjob', ['slurm_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sbatchjob_slurm_id'), table_name='sbatchjob')
    op.drop_table('sbatchjob')
    SLURM_JOB_STATE.drop(op.get_bind())
    SLURM_JOB_STATUS_ENUM.create(op.get_bind())
    op.add_column('sbatchanalysisspec', sa.Column('status', SLURM_JOB_STATUS_ENUM, nullable=False, default='UNSUBMITTED'))
    # ### end Alembic commands ###
