"""Add wellplates

Revision ID: 161ceb9faae3
Revises: ecb7aab3e7df
Create Date: 2024-10-24 13:04:20.474151

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '161ceb9faae3'
down_revision = 'ecb7aab3e7df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wellplate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plate_type', sa.Enum('REVVITY_PHENOPLATE_96', name='wellplatetype'), nullable=False),
    sa.Column('location', sa.Enum('CQ1', 'KX2', 'CYTOMAT2', name='location'), nullable=True),
    sa.Column('record_created', sa.DateTime(), nullable=False),
    sa.Column('last_location_update', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wellplate_name'), 'wellplate', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wellplate_name'), table_name='wellplate')
    op.drop_table('wellplate')
    # ### end Alembic commands ###
    op.execute("DROP TYPE wellplatetype")
    op.execute("DROP TYPE location")
