"""Add wellplates

Revision ID: 161ceb9faae3
Revises: ecb7aab3e7df
Create Date: 2024-10-24 13:04:20.474151

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision = '161ceb9faae3'
down_revision = 'ecb7aab3e7df'
branch_labels = None
depends_on = None

WELLPLATE_ENUM = sa.Enum("REVVITY_PHENOPLATE_96", name="wellplatetype")
LOCATION_ENUM = sa.Enum("CQ1", "KX2", "CYTOMAT2", "HOTEL", name="location")

def upgrade():
    WELLPLATE_ENUM.create(op.get_bind())
    LOCATION_ENUM.create(op.get_bind())

    op.create_table('wellplate',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('record_created', sa.DateTime(), nullable=False),
        sa.Column('last_update', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column('wellplate', sa.Column('plate_type', WELLPLATE_ENUM, nullable=False))
    op.add_column('wellplate', sa.Column('location', LOCATION_ENUM, nullable=True))
    op.create_index(op.f('ix_wellplate_name'), 'wellplate', ['name'], unique=True)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wellplate_name'), table_name='wellplate')
    op.drop_table('wellplate')
    # ### end Alembic commands ###
    WELLPLATE_ENUM.drop(op.get_bind())
    LOCATION_ENUM.drop(op.get_bind())
