"""add optional storage_position field to acquisitionpplan

Revision ID: 21aa175324fd
Revises: f12b5bb4962a
Create Date: 2025-02-06 12:42:14.805305

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '21aa175324fd'
down_revision = 'f12b5bb4962a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acquisitionplan', sa.Column('storage_position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('acquisitionplan', 'storage_position')
    # ### end Alembic commands ###
