"""Invert Aquisition-AcquisitionPlan relationship

Revision ID: 26a220ee370f
Revises: c8393dab42fa
Create Date: 2024-11-25 18:02:20.205340

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '26a220ee370f'
down_revision = 'c8393dab42fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('acquisition_acquisition_plan_id_fkey', 'acquisition', type_='foreignkey')
    op.drop_column('acquisition', 'acquisition_plan_id')
    op.add_column('acquisitionplan', sa.Column('acquisition_id', sa.Integer(), nullable=False))
    op.create_foreign_key("acquisition_plan_acquisition_id_fkey", 'acquisitionplan', 'acquisition', ['acquisition_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("acquisition_plan_acquisition_id_fkey", 'acquisitionplan', type_='foreignkey')
    op.drop_column('acquisitionplan', 'acquisition_id')
    op.add_column('acquisition', sa.Column('acquisition_plan_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('acquisition_acquisition_plan_id_fkey', 'acquisition', 'acquisitionplan', ['acquisition_plan_id'], ['id'])
    # ### end Alembic commands ###
