"""Add artifacts

Revision ID: 2d198002d430
Revises: 9d12dad27d25
Create Date: 2024-11-25 12:41:37.305667

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2d198002d430'
down_revision = '9d12dad27d25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['artifactcollection.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('artifactcollection_acquisition_id_fkey', 'artifactcollection', type_='foreignkey')
    op.create_foreign_key(None, 'artifactcollection', 'acquisition', ['acquisition_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'artifactcollection', type_='foreignkey')
    op.create_foreign_key('artifactcollection_acquisition_id_fkey', 'artifactcollection', 'acquisition', ['acquisition_id'], ['id'])
    op.drop_table('artifact')
    # ### end Alembic commands ###
