"""Add unique constraints

Revision ID: 567c76c2ca3e
Revises: 5b842981ce4b
Create Date: 2024-11-26 10:15:05.264666

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '567c76c2ca3e'
down_revision = '5b842981ce4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("acquisitionplan_aquisition_id_unique", 'acquisitionplan', ['acquisition_id'])
    op.create_unique_constraint("analysisplan_acquisition_id_unique", 'analysisplan', ['acquisition_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("analysisplan_acquisition_id_unique", 'analysisplan', type_='unique')
    op.drop_constraint("acquisitionplan_aquisition_id_unique", 'acquisitionplan', type_='unique')
    # ### end Alembic commands ###
