"""Update cascading deletes for wellplates, acquisition plans, and plateread specs

Revision ID: 56e1606c4a25
Revises: 89097936902c
Create Date: 2024-11-08 15:22:35.954572

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '56e1606c4a25'
down_revision = '89097936902c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('acquisitionplan_wellplate_id_fkey', 'acquisitionplan', type_='foreignkey')
    op.create_foreign_key(None, 'acquisitionplan', 'wellplate', ['wellplate_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('platereadspec_acquisition_plan_id_fkey', 'platereadspec', type_='foreignkey')
    op.create_foreign_key(None, 'platereadspec', 'acquisitionplan', ['acquisition_plan_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'platereadspec', type_='foreignkey')
    op.create_foreign_key('platereadspec_acquisition_plan_id_fkey', 'platereadspec', 'acquisitionplan', ['acquisition_plan_id'], ['id'])
    op.drop_constraint(None, 'acquisitionplan', type_='foreignkey')
    op.create_foreign_key('acquisitionplan_wellplate_id_fkey', 'acquisitionplan', 'wellplate', ['wellplate_id'], ['id'])
    # ### end Alembic commands ###
