"""Drop name from acquisitionplan

Revision ID: 5b842981ce4b
Revises: a0e3aafe0d70
Create Date: 2024-11-25 18:21:32.444370

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5b842981ce4b'
down_revision = 'a0e3aafe0d70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_acquisitionplan_name', table_name='acquisitionplan')
    op.drop_column('acquisitionplan', 'name')
    op.add_column('sbatchanalysisspec', sa.Column('analysis_status', sa.Enum('PENDING', 'SCHEDULED', 'RUNNING', 'COMPLETED', 'CANCELLED', 'ABORTED', 'RESET', name='processstatus'), nullable=False))
    op.drop_column('sbatchanalysisspec', 'process_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sbatchanalysisspec', sa.Column('process_status', postgresql.ENUM('PENDING', 'SCHEDULED', 'RUNNING', 'COMPLETED', 'CANCELLED', 'ABORTED', 'RESET', name='processstatus'), autoincrement=False, nullable=False))
    op.drop_column('sbatchanalysisspec', 'analysis_status')
    op.add_column('acquisitionplan', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_index('ix_acquisitionplan_name', 'acquisitionplan', ['name'], unique=True)
    # ### end Alembic commands ###
