"""add is_active field to acquisition

Revision ID: 63b126facc06
Revises: d6eb1211ef4f
Create Date: 2024-12-23 14:04:09.423127

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '63b126facc06'
down_revision = 'd6eb1211ef4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acquisition', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('acquisition', 'is_active')
    # ### end Alembic commands ###
