"""fix instrument ondelete behavior

Revision ID: 6845efc2a64c
Revises: 15149a846727
Create Date: 2025-04-08 18:01:46.808877

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6845efc2a64c'
down_revision = '15149a846727'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('acquisition_instrument_id_fkey', 'acquisition', type_='foreignkey')
    op.create_foreign_key(None, 'acquisition', 'instrument', ['instrument_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint('instrument_instrument_type_id_fkey', 'instrument', type_='foreignkey')
    op.create_foreign_key(None, 'instrument', 'instrumenttype', ['instrument_type_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'instrument', type_='foreignkey')
    op.create_foreign_key('instrument_instrument_type_id_fkey', 'instrument', 'instrumenttype', ['instrument_type_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'acquisition', type_='foreignkey')
    op.create_foreign_key('acquisition_instrument_id_fkey', 'acquisition', 'instrument', ['instrument_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
