"""make deadline_delta optional

Revision ID: 6d42703c7fad
Revises: 12e238b646e8
Create Date: 2025-01-17 13:09:19.600785

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6d42703c7fad'
down_revision = '12e238b646e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('acquisitionplan', 'deadline_delta',
               existing_type=postgresql.INTERVAL(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # don't want to bother supporting downgrades for this migration
    # ### end Alembic commands ###
    pass
