"""Add Acquisitions and Artifacts

Revision ID: 89097936902c
Revises: e95562d1f295
Create Date: 2024-11-04 15:07:06.699399

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '89097936902c'
down_revision = 'e95562d1f295'
branch_labels = None
depends_on = None

REPOSITORY = sa.Enum('ACQUISITION', 'ARCHIVE', 'ANALYSIS', name='repository')
ARTIFACT_TYPE = sa.Enum('ACQUISITION', 'ANALYSIS', name='artifacttype')

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acquisition',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acquisition_plan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['acquisition_plan_id'], ['acquisitionplan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acquisition_name'), 'acquisition', ['name'], unique=True)
    op.create_table('artifactcollection',
    sa.Column('record_created', sa.DateTime(), nullable=False),
    sa.Column('last_update', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acquisition_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['acquisition_id'], ['acquisition.id'], ),
    sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###
    REPOSITORY.create(op.get_bind())
    ARTIFACT_TYPE.create(op.get_bind())
    op.add_column('artifactcollection', sa.Column('location', REPOSITORY, nullable=False))
    op.add_column('artifactcollection', sa.Column('artifact_type', ARTIFACT_TYPE, nullable=False))

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artifactcollection')
    op.drop_index(op.f('ix_acquisition_name'), table_name='acquisition')
    op.drop_table('acquisition')
    # ### end Alembic commands ###
    REPOSITORY.drop(op.get_bind())
    ARTIFACT_TYPE.drop(op.get_bind())
