"""add instruments

Revision ID: 943886ce0962
Revises: 6d42703c7fad
Create Date: 2025-01-23 13:45:48.646363

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '943886ce0962'
down_revision = '6d42703c7fad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    instrument_type = op.create_table('instrumenttype',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instrumenttype_name'), 'instrumenttype', ['name'], unique=True)
    instrument_table = op.create_table('instrument',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_type_id'], ['instrumenttype.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_index(op.f('ix_instrument_name'), 'instrument', ['name'], unique=True)
    op.add_column('acquisition', sa.Column('instrument_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

    # populate instruments with default values and assign to acquisition.instrument_id
    insert_result = op.get_bind().execute(
        sa.insert(instrument_type)
        .values([{"name":"IMAGING"}, {"name":"PCR"}])
        .returning(column("id"), column("name")),
    ).all()

    type_ids = {name: id for id, name in insert_result}

    op.execute(
        f"""
        INSERT INTO instrument (name, instrument_type_id) VALUES ('CQ1', {type_ids['IMAGING']}), ('QuantStudio3', {type_ids['PCR']})
        RETURNING id, name
        """
    )
    op.execute(
        """
        UPDATE acquisition SET instrument_id = 1
        WHERE instrument_id IS NULL
        """
    )
    op.alter_column('acquisition', 'instrument_id', nullable=False)
    op.create_foreign_key('acquisition_instrument_id_fkey', 'acquisition', 'instrument', ['instrument_id'], ['id'], ondelete='CASCADE')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('acquisition_instrument_id_fkey', 'acquisition', type_='foreignkey')
    op.drop_column('acquisition', 'instrument_id')
    op.drop_index(op.f('ix_instrument_name'), table_name='instrument')
    op.drop_table('instrument')
    op.drop_index(op.f('ix_instrumenttype_name'), table_name='instrumenttype')
    op.drop_table('instrumenttype')
    # ### end Alembic commands ###
