"""Create analysis plan

Revision ID: a0e3aafe0d70
Revises: 26a220ee370f
Create Date: 2024-11-25 18:03:42.986920

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a0e3aafe0d70'
down_revision = '26a220ee370f'
branch_labels = None
depends_on = None


PROCESS_STATUS_ENUM = sa.Enum('PENDING', 'SCHEDULED', 'RUNNING', 'COMPLETED', 'CANCELLED', 'ABORTED', 'RESET', name='processstatus')

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysisplan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acquisition_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['acquisition_id'], ['acquisition.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sbatchanalysisspec',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_cmd', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('analysis_args', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('analysis_plan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_plan_id'], ['analysisplan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('sbatchanalysisspec', sa.Column('process_status', PROCESS_STATUS_ENUM, nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sbatchanalysisspec')
    op.drop_table('analysisplan')
    # ### end Alembic commands ###
