"""Add trigger to analysis

Revision ID: c0d8b66a58ee
Revises: 567c76c2ca3e
Create Date: 2024-11-26 12:57:54.247576

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c0d8b66a58ee'
down_revision = '567c76c2ca3e'
branch_labels = None
depends_on = None


ANALYSIS_TRIGGER = sa.Enum('POST_ACQUISTION', 'POST_READ', name='analysistrigger')

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    ANALYSIS_TRIGGER.create(op.get_bind())
    op.add_column('sbatchanalysisspec', sa.Column('trigger', ANALYSIS_TRIGGER, nullable=False))
    op.add_column('sbatchanalysisspec', sa.Column('trigger_value', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sbatchanalysisspec', 'trigger_value')
    op.drop_column('sbatchanalysisspec', 'trigger')
    ANALYSIS_TRIGGER.drop(op.get_bind())
    # ### end Alembic commands ###
