"""Add 'SUBMITTED' slurm job status

Revision ID: c524e0afa9f7
Revises: 6482928619ad
Create Date: 2024-12-05 15:40:45.030213

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c524e0afa9f7'
down_revision = '6482928619ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE slurmjobstatus ADD VALUE 'SUBMITTED';")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # not possible to remove values from an enum in postgresql :shrug:
    pass
    # ### end Alembic commands ###
