"""Rename PlateReadStatus to ProcessStatus

Revision ID: c8393dab42fa
Revises: 2d198002d430
Create Date: 2024-11-25 18:01:22.876128

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c8393dab42fa'
down_revision = '2d198002d430'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE platereadstatus RENAME TO processstatus;")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE processstatus RENAME TO platereadstatus;")
    # ### end Alembic commands ###
