"""add unique constraint to sbatch analysis

Revision ID: d6eb1211ef4f
Revises: c524e0afa9f7
Create Date: 2024-12-19 12:42:25.841519

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd6eb1211ef4f'
down_revision = 'c524e0afa9f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_sbatch_analysis_per_plan', 'sbatchanalysisspec', ['analysis_plan_id', 'analysis_cmd', 'analysis_args'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_sbatch_analysis_per_plan', 'sbatchanalysisspec', type_='unique')
    # ### end Alembic commands ###
