"""Add unique constraint to ArtifactCollection

Revision ID: d8b2902c8d27
Revises: c0d8b66a58ee
Create Date: 2024-11-26 13:46:21.021859

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd8b2902c8d27'
down_revision = 'c0d8b66a58ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_acquisition_collection', 'artifactcollection', ['acquisition_id', 'artifact_type', 'location'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_acquisition_collection', 'artifactcollection', type_='unique')
    # ### end Alembic commands ###
