"""Add acquisition plans

Revision ID: e95562d1f295
Revises: 161ceb9faae3
Create Date: 2024-10-29 12:51:54.569038

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e95562d1f295'
down_revision = '161ceb9faae3'
branch_labels = None
depends_on = None


LOCATION_ENUM = sa.Enum('CQ1', 'KX2', 'CYTOMAT2', 'HOTEL', name='location')
PRIORITY_ENUM = sa.Enum('NORMAL', 'LOW', name='imagingpriority')
PLATEREAD_STATUS_ENUM = sa.Enum('PENDING', 'SCHEDULED', 'RUNNING', 'COMPLETED', 'CANCELLED', 'ABORTED', 'RESET', name='platereadstatus')

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acquisitionplan',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('wellplate_id', sa.Integer(), nullable=False),
    sa.Column('interval', sa.Interval(), nullable=False),
    sa.Column('deadline_delta', sa.Interval(), nullable=False),
    sa.Column('protocol_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('n_reads', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['wellplate_id'], ['wellplate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acquisitionplan_name'), 'acquisitionplan', ['name'], unique=True)
    op.create_table('platereadspec',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_after', sa.DateTime(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('acquisition_plan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['acquisition_plan_id'], ['acquisitionplan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    PLATEREAD_STATUS_ENUM.create(op.get_bind())
    PRIORITY_ENUM.create(op.get_bind())
    op.add_column('acquisitionplan', sa.Column('storage_location', LOCATION_ENUM, nullable=False))
    op.add_column('acquisitionplan', sa.Column('priority', PRIORITY_ENUM, nullable=False))
    op.add_column('platereadspec', sa.Column('status', PLATEREAD_STATUS_ENUM, nullable=False))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('platereadspec')
    op.drop_index(op.f('ix_acquisitionplan_name'), table_name='acquisitionplan')
    op.drop_table('acquisitionplan')
    # ### end Alembic commands ###
    PLATEREAD_STATUS_ENUM.drop(op.get_bind())
    PRIORITY_ENUM.drop(op.get_bind())
